<a href="https://colab.research.google.com/github/BYEONGSEOKKIM/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np

data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
data2 =[0,1,5,4,12,0.5]
a2 = np.array(data2)
a2

array([ 0. ,  1. ,  5. ,  4. , 12. ,  0.5])

In [5]:
a1.dtype

dtype('int64')

In [6]:
a2.dtype

dtype('float64')

In [7]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

In [10]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [19]:
b2 = np.arange(5)
b2.shape

(5,)

In [20]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.array(['0.5','0.62','2','3.14','3.141592'])

array(['0.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [28]:
str_a1 = np.array(['1.567','0.123','5.123','9','8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [29]:
str_a1.dtype

dtype('<U5')

In [32]:
num_a1.dtype

dtype('float64')

In [33]:
str_a2 = np.array(['1','3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [34]:
str_a2.dtype

dtype('<U1')

In [35]:
num_a2.dtype

dtype('int64')

In [36]:
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [39]:
num_f1.dtype


dtype('float64')

In [41]:
num_i1.dtype

dtype('int64')

In [46]:
np.random.rand(2,3)

array([[0.90117263, 0.87673058, 0.65108793],
       [0.29374338, 0.49843201, 0.12691396]])

In [44]:
np.random.rand()

0.9828655769508288

In [53]:
np.random.rand(2,3,4)

array([[[0.57873064, 0.04588622, 0.7239929 , 0.43398956],
        [0.0448361 , 0.34191566, 0.79500516, 0.12173415],
        [0.527795  , 0.51345475, 0.72780771, 0.71938917]],

       [[0.29565924, 0.08366973, 0.31323268, 0.78874514],
        [0.73427943, 0.10347248, 0.04808843, 0.34155127],
        [0.04404215, 0.45845519, 0.88395955, 0.8453356 ]]])

In [48]:
np.random.randint(10,size=(3,4))

array([[8, 9, 8, 9],
       [9, 3, 1, 5],
       [4, 1, 4, 5]])

In [49]:
np.random.randint(1,30)

16

In [52]:
np.random.randint(3,size=(3,4))

array([[1, 1, 0, 0],
       [2, 1, 0, 1],
       [0, 1, 1, 2]])

In [54]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [55]:
arr1 + arr2

array([11, 22, 33, 44])

In [56]:
arr1-arr2

array([ 9, 18, 27, 36])

In [57]:
arr2*2

array([2, 4, 6, 8])

In [58]:
arr2**2

array([ 1,  4,  9, 16])

In [59]:
arr1*arr2

array([ 10,  40,  90, 160])

In [60]:
arr1/arr2

array([10., 10., 10., 10.])

In [62]:
arr1 / (arr2**2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [63]:
arr1 >20

array([False, False,  True,  True])

In [64]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [65]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [67]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [69]:
[arr3.min(), arr3.max()]

[0, 4]

In [71]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [72]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [73]:
arr4.cumprod()

array([ 1,  2,  6, 24])

In [74]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [76]:
B= np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [77]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [78]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [80]:
np.transpose(A)
A.transpose()

array([[0, 2],
       [1, 3]])

In [81]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [82]:
np.linalg.det(A)

-2.0

In [83]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [84]:
a1[0]

0

In [85]:
a1[4]

40

In [86]:
a1[5]=70
a1

array([ 0, 10, 20, 30, 40, 70])

In [87]:
a1[[1,3,4]]

array([10, 30, 40])

In [88]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [89]:
a2[0,2]

30

In [90]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [91]:
a2[1]

array([40, 50, 60])

In [92]:
a2[1]=np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [93]:
a2[1]=[47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [94]:
a2[[0,2],[0,1]]

array([10, 80])

In [95]:
a= np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [96]:
a[(a%2) == 0]

array([2, 4, 6])

In [97]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [98]:
b1[:3]

array([ 0, 10, 20])

In [99]:
b1[2:]

array([20, 30, 40, 50])

In [101]:
b1[2:5]=np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [102]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [103]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [104]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [105]:
b2[:3,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [106]:
b2[1][0:2]

array([40, 50])

In [109]:
b2[0:2, 1:3] = np.array([[25,35], [55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])